[package]
name = "servicesaccountlinking"
description = "Apple ServicesAccountLinking — service account linking from Rust"
version = "0.0.1"
edition = "2021"
license = "Apache-2.0"

[lib]
name = "servicesaccountlinking"

[dependencies]
apple-sys-helpers = { workspace = true }

[lints]
workspace = true
