[package]
name = "swiftui"
description = "Build SwiftUI views from Rust"
version = "0.0.3"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/eugenehp/swift-runtime-sys"
keywords = ["swift", "swiftui", "gui", "macos", "ui"]

[lib]
name = "swiftui"

[features]
default = []
# macOS deployment target
macos-15 = []
macos-26 = []
# iOS deployment target
ios-18 = []
ios-26 = []

[dependencies]
swift-runtime-sys = { path = "../swift-runtime-sys" }
swift-runtime = { path = "../swift-runtime" }
swiftui-sys = { path = "../swiftui-sys" }
swiftui-macros = { path = "../swiftui-macros" }
libc = "0.2"

[[example]]
name = "app_notes"
path = "examples/app_notes/main.rs"

[[example]]
name = "app_dashboard"
path = "examples/app_dashboard/main.rs"
