//! Raw FFI bindings to SwiftUI via a generated Swift `@_cdecl` bridge.
//!
//! This crate is auto-generated by `swift-bridge-gen`. Do not edit manually.
//! The ergonomic API is in the `swiftui` crate.
//!
//! All functions require `libSwiftUIBridge.dylib` to be loaded via `dlopen`
//! before use. Use [`load`] to load and resolve all symbols.

#![allow(non_snake_case, dead_code)]

use core::ffi::{c_char, c_void};
use std::ffi::CString;

pub type Handle = *mut c_void;

unsafe extern "C" {
    fn dlopen(path: *const c_char, mode: i32) -> *mut c_void;
    fn dlsym(handle: *mut c_void, symbol: *const c_char) -> *mut c_void;
}

fn sym(h: *mut c_void, name: &core::ffi::CStr) -> *mut c_void {
    let p = unsafe { dlsym(h, name.as_ptr()) };
    assert!(!p.is_null(), "Symbol not found: {}", name.to_str().unwrap());
    p
}

/// All resolved function pointers from the Swift bridge dylib.
pub struct Fns {
    // Views
    pub text: unsafe extern "C" fn(*const u8, usize) -> Handle,
    pub styled_text: unsafe extern "C" fn(*const u8, usize, f32, i32, f32, f32, f32, f32) -> Handle,
    pub system_image: unsafe extern "C" fn(*const u8, usize) -> Handle,
    pub spacer: unsafe extern "C" fn() -> Handle,
    pub divider: unsafe extern "C" fn() -> Handle,
    pub color: unsafe extern "C" fn(f32, f32, f32, f32) -> Handle,
    pub progress: unsafe extern "C" fn(f32, f32) -> Handle,
    pub toggle: unsafe extern "C" fn(*const u8, usize, bool) -> Handle,
    pub textfield: unsafe extern "C" fn(*const u8, usize, *const u8, usize) -> Handle,
    pub button: unsafe extern "C" fn(
        *const u8,
        usize,
        unsafe extern "C" fn(*mut c_void),
        *mut c_void,
    ) -> Handle,

    // Stacks
    pub vstack: unsafe extern "C" fn(*const Handle, usize) -> Handle,
    pub hstack: unsafe extern "C" fn(*const Handle, usize) -> Handle,
    pub zstack: unsafe extern "C" fn(*const Handle, usize) -> Handle,
    pub scroll_view: unsafe extern "C" fn(Handle) -> Handle,

    // Modifiers
    pub padding: unsafe extern "C" fn(Handle, f32) -> Handle,
    pub frame: unsafe extern "C" fn(Handle, f32, f32) -> Handle,
    pub background_color: unsafe extern "C" fn(Handle, f32, f32, f32, f32) -> Handle,
    pub corner_radius: unsafe extern "C" fn(Handle, f32) -> Handle,
    pub opacity: unsafe extern "C" fn(Handle, f32) -> Handle,
    pub border: unsafe extern "C" fn(Handle, f32, f32, f32, f32) -> Handle,

    // Lifecycle
    pub release: unsafe extern "C" fn(Handle),
    pub retain: unsafe extern "C" fn(Handle),

    // Window
    pub show_window: unsafe extern "C" fn(Handle, *const u8, usize, f32, f32),

    // Snapshot (optional — may be null)
    pub snapshot:
        Option<unsafe extern "C" fn(Handle, f32, f32, *mut *mut c_void, *mut usize) -> bool>,
    pub snapshot_free: Option<unsafe extern "C" fn(*mut c_void, usize)>,
    pub compare_png:
        Option<unsafe extern "C" fn(*const c_void, usize, *const c_void, usize, f32) -> f32>,
}

/// Load the Swift bridge dylib and resolve all symbols.
pub fn load(path: &str) -> Result<Fns, String> {
    unsafe {
        // Load SwiftUI framework
        dlopen(
            c"/System/Library/Frameworks/SwiftUI.framework/SwiftUI".as_ptr(),
            1,
        );

        let cpath = CString::new(path).unwrap();
        let h = dlopen(cpath.as_ptr(), 2);
        if h.is_null() {
            return Err(format!("Failed to load {path}"));
        }

        let snap_ptr = dlsym(h, c"snapshot_view_handle".as_ptr());
        let free_ptr = dlsym(h, c"free_snapshot".as_ptr());
        let cmp_ptr = dlsym(h, c"compare_png_bytes".as_ptr());

        Ok(Fns {
            text: std::mem::transmute(sym(h, c"swiftui_text")),
            styled_text: std::mem::transmute(sym(h, c"swiftui_text_styled")),
            system_image: std::mem::transmute(sym(h, c"swiftui_system_image")),
            spacer: std::mem::transmute(sym(h, c"swiftui_spacer")),
            divider: std::mem::transmute(sym(h, c"swiftui_divider")),
            color: std::mem::transmute(sym(h, c"swiftui_color")),
            progress: std::mem::transmute(sym(h, c"swiftui_progress")),
            toggle: std::mem::transmute(sym(h, c"swiftui_toggle")),
            textfield: std::mem::transmute(sym(h, c"swiftui_textfield")),
            button: std::mem::transmute(sym(h, c"swiftui_button")),
            vstack: std::mem::transmute(sym(h, c"swiftui_vstack")),
            hstack: std::mem::transmute(sym(h, c"swiftui_hstack")),
            zstack: std::mem::transmute(sym(h, c"swiftui_zstack")),
            scroll_view: std::mem::transmute(sym(h, c"swiftui_scroll_view")),
            padding: std::mem::transmute(sym(h, c"swiftui_padding")),
            frame: std::mem::transmute(sym(h, c"swiftui_frame")),
            background_color: std::mem::transmute(sym(h, c"swiftui_background_color")),
            corner_radius: std::mem::transmute(sym(h, c"swiftui_corner_radius")),
            opacity: std::mem::transmute(sym(h, c"swiftui_opacity")),
            border: std::mem::transmute(sym(h, c"swiftui_border")),
            release: std::mem::transmute(sym(h, c"swiftui_release")),
            retain: std::mem::transmute(sym(h, c"swiftui_retain")),
            show_window: std::mem::transmute(sym(h, c"swiftui_show_window")),
            snapshot: if snap_ptr.is_null() {
                None
            } else {
                Some(std::mem::transmute(snap_ptr))
            },
            snapshot_free: if free_ptr.is_null() {
                None
            } else {
                Some(std::mem::transmute(free_ptr))
            },
            compare_png: if cmp_ptr.is_null() {
                None
            } else {
                Some(std::mem::transmute(cmp_ptr))
            },
        })
    }
}
