//! Raw FFI bindings to SwiftUI via a generated Swift `@_cdecl` bridge.
//!
//! This crate is auto-generated by `swift-bridge-gen`. Do not edit manually.
//! The ergonomic API is in the `swiftui` crate.
//!
//! All functions require `libSwiftUIBridge.dylib` to be loaded via `dlopen`
//! before use. Use [`load`] to load and resolve all symbols.

#![allow(non_snake_case, dead_code)]

use core::ffi::{c_char, c_void};
use std::ffi::CString;

pub type Handle = *mut c_void;

unsafe extern "C" {
    fn dlopen(path: *const c_char, mode: i32) -> *mut c_void;
    fn dlsym(handle: *mut c_void, symbol: *const c_char) -> *mut c_void;
}

fn sym(h: *mut c_void, name: &core::ffi::CStr) -> *mut c_void {
    let p = unsafe { dlsym(h, name.as_ptr()) };
    assert!(!p.is_null(), "Symbol not found: {}", name.to_str().unwrap());
    p
}

/// All resolved function pointers from the Swift bridge dylib.
pub struct Fns {
    // Views
    pub text: unsafe extern "C" fn(*const u8, usize) -> Handle,
    pub styled_text: unsafe extern "C" fn(*const u8, usize, f32, i32, f32, f32, f32, f32) -> Handle,
    pub system_image: unsafe extern "C" fn(*const u8, usize) -> Handle,
    pub spacer: unsafe extern "C" fn() -> Handle,
    pub divider: unsafe extern "C" fn() -> Handle,
    pub color: unsafe extern "C" fn(f32, f32, f32, f32) -> Handle,
    pub progress: unsafe extern "C" fn(f32, f32) -> Handle,
    pub toggle: unsafe extern "C" fn(*const u8, usize, bool) -> Handle,
    pub textfield: unsafe extern "C" fn(*const u8, usize, *const u8, usize) -> Handle,
    pub button: unsafe extern "C" fn(
        *const u8,
        usize,
        unsafe extern "C" fn(*mut c_void),
        *mut c_void,
    ) -> Handle,

    // Stacks
    pub vstack: unsafe extern "C" fn(*const Handle, usize) -> Handle,
    pub hstack: unsafe extern "C" fn(*const Handle, usize) -> Handle,
    pub zstack: unsafe extern "C" fn(*const Handle, usize) -> Handle,
    pub scroll_view: unsafe extern "C" fn(Handle) -> Handle,

    // Modifiers
    pub padding: unsafe extern "C" fn(Handle, f32) -> Handle,
    pub frame: unsafe extern "C" fn(Handle, f32, f32) -> Handle,
    pub background_color: unsafe extern "C" fn(Handle, f32, f32, f32, f32) -> Handle,
    pub corner_radius: unsafe extern "C" fn(Handle, f32) -> Handle,
    pub opacity: unsafe extern "C" fn(Handle, f32) -> Handle,
    pub border: unsafe extern "C" fn(Handle, f32, f32, f32, f32) -> Handle,
    pub foreground_color: unsafe extern "C" fn(Handle, f32, f32, f32, f32) -> Handle,
    pub shadow: unsafe extern "C" fn(Handle, f32, f32, f32, f32, f32, f32) -> Handle,
    pub offset: unsafe extern "C" fn(Handle, f32, f32) -> Handle,
    pub scale: unsafe extern "C" fn(Handle, f32) -> Handle,
    pub rotation: unsafe extern "C" fn(Handle, f32) -> Handle,
    pub hidden: unsafe extern "C" fn(Handle) -> Handle,
    pub disabled: unsafe extern "C" fn(Handle, bool) -> Handle,
    pub overlay: unsafe extern "C" fn(Handle, Handle) -> Handle,
    pub clip_circle: unsafe extern "C" fn(Handle) -> Handle,
    pub font_system: unsafe extern "C" fn(Handle, f32, i32) -> Handle,

    // Additional views
    pub label: unsafe extern "C" fn(*const u8, usize, *const u8, usize) -> Handle,
    pub slider: unsafe extern "C" fn(f32, f32, f32) -> Handle,
    pub link: unsafe extern "C" fn(*const u8, usize, *const u8, usize) -> Handle,

    // Gestures
    pub on_tap:
        unsafe extern "C" fn(Handle, unsafe extern "C" fn(*mut c_void), *mut c_void) -> Handle,
    pub on_long_press:
        unsafe extern "C" fn(Handle, unsafe extern "C" fn(*mut c_void), *mut c_void) -> Handle,

    // Bound controls
    pub bound_textfield: unsafe extern "C" fn(
        *const u8,
        usize,
        *const u8,
        usize,
        unsafe extern "C" fn(*const u8, usize, *mut c_void),
        *mut c_void,
    ) -> Handle,
    pub bound_toggle: unsafe extern "C" fn(
        *const u8,
        usize,
        bool,
        unsafe extern "C" fn(bool, *mut c_void),
        *mut c_void,
    ) -> Handle,
    pub bound_slider: unsafe extern "C" fn(
        f32,
        f32,
        f32,
        unsafe extern "C" fn(f32, *mut c_void),
        *mut c_void,
    ) -> Handle,

    // List / Sheet / Alert / Animation
    pub list: unsafe extern "C" fn(*const Handle, usize) -> Handle,
    pub sheet: unsafe extern "C" fn(Handle, Handle, bool) -> Handle,
    pub alert: unsafe extern "C" fn(Handle, *const u8, usize, *const u8, usize, bool) -> Handle,
    pub animation: unsafe extern "C" fn(Handle, i32) -> Handle,

    // Extra modifiers
    pub blur: unsafe extern "C" fn(Handle, f32) -> Handle,
    pub brightness: unsafe extern "C" fn(Handle, f32) -> Handle,
    pub saturation: unsafe extern "C" fn(Handle, f32) -> Handle,
    pub grayscale: unsafe extern "C" fn(Handle, f32) -> Handle,
    pub help_text: unsafe extern "C" fn(Handle, *const u8, usize) -> Handle,
    pub line_limit: unsafe extern "C" fn(Handle, i32) -> Handle,
    pub fixed_size_mod: unsafe extern "C" fn(Handle) -> Handle,
    pub aspect_ratio: unsafe extern "C" fn(Handle, f32, i32) -> Handle,
    pub clipped: unsafe extern "C" fn(Handle) -> Handle,
    pub tint: unsafe extern "C" fn(Handle, f32, f32, f32) -> Handle,
    pub badge: unsafe extern "C" fn(Handle, i32) -> Handle,

    // Extra views
    pub secure_field: unsafe extern "C" fn(*const u8, usize, *const u8, usize) -> Handle,
    pub text_editor: unsafe extern "C" fn(*const u8, usize) -> Handle,
    pub stepper: unsafe extern "C" fn(*const u8, usize, i32, i32, i32) -> Handle,
    pub group_box: unsafe extern "C" fn(*const u8, usize, Handle) -> Handle,

    // TabView / Picker / Menu
    pub tabview: unsafe extern "C" fn(
        *const Handle,
        *const *const u8,
        *const usize,
        *const *const u8,
        *const usize,
        usize,
    ) -> Handle,
    pub bound_picker: unsafe extern "C" fn(
        *const u8,
        usize,
        *const *const u8,
        *const usize,
        usize,
        i32,
        unsafe extern "C" fn(i32, *mut c_void),
        *mut c_void,
    ) -> Handle,
    pub menu: unsafe extern "C" fn(*const u8, usize, Handle) -> Handle,
    pub context_menu: unsafe extern "C" fn(Handle, Handle) -> Handle,

    // Nav / Toolbar / Grid / Form
    pub navigation_title: unsafe extern "C" fn(Handle, *const u8, usize) -> Handle,
    pub toolbar: unsafe extern "C" fn(Handle, Handle) -> Handle,
    pub grid: unsafe extern "C" fn(*const Handle, usize, i32) -> Handle,
    pub form: unsafe extern "C" fn(*const Handle, usize) -> Handle,
    pub section: unsafe extern "C" fn(*const u8, usize, *const Handle, usize) -> Handle,

    // Per-view lifecycle
    pub on_appear:
        unsafe extern "C" fn(Handle, unsafe extern "C" fn(*mut c_void), *mut c_void) -> Handle,
    pub on_disappear:
        unsafe extern "C" fn(Handle, unsafe extern "C" fn(*mut c_void), *mut c_void) -> Handle,

    // Bold / Italic on any view
    pub bold_mod: unsafe extern "C" fn(Handle) -> Handle,
    pub italic_mod: unsafe extern "C" fn(Handle) -> Handle,

    // Popover
    pub popover: unsafe extern "C" fn(Handle, Handle, bool) -> Handle,

    // Remaining modifiers
    pub color_invert: unsafe extern "C" fn(Handle) -> Handle,
    pub ignores_safe_area: unsafe extern "C" fn(Handle) -> Handle,
    pub confirmation_dialog: unsafe extern "C" fn(Handle, *const u8, usize, bool, Handle) -> Handle,
    pub keyboard_shortcut: unsafe extern "C" fn(Handle, *const u8, usize) -> Handle,
    pub focusable: unsafe extern "C" fn(Handle) -> Handle,
    pub truncation_mode: unsafe extern "C" fn(Handle, i32) -> Handle,
    pub multiline_alignment: unsafe extern "C" fn(Handle, i32) -> Handle,
    pub minimum_scale_factor: unsafe extern "C" fn(Handle, f32) -> Handle,

    // Accessibility
    pub accessibility_label: unsafe extern "C" fn(Handle, *const u8, usize) -> Handle,
    pub accessibility_hint: unsafe extern "C" fn(Handle, *const u8, usize) -> Handle,
    pub accessibility_hidden: unsafe extern "C" fn(Handle, bool) -> Handle,
    pub accessibility_value: unsafe extern "C" fn(Handle, *const u8, usize) -> Handle,

    // Remaining views
    pub disclosure_group: unsafe extern "C" fn(*const u8, usize, Handle) -> Handle,
    pub labeled_content: unsafe extern "C" fn(*const u8, usize, Handle) -> Handle,
    pub navigation_split_view: unsafe extern "C" fn(Handle, Handle) -> Handle,
    pub content_unavailable:
        unsafe extern "C" fn(*const u8, usize, *const u8, usize, *const u8, usize) -> Handle,
    pub share_link: unsafe extern "C" fn(*const u8, usize, *const u8, usize) -> Handle,

    // Lifecycle
    pub release: unsafe extern "C" fn(Handle),
    pub retain: unsafe extern "C" fn(Handle),

    // Window
    pub show_window: unsafe extern "C" fn(Handle, *const u8, usize, f32, f32),

    // Snapshot (optional — may be null)
    pub snapshot:
        Option<unsafe extern "C" fn(Handle, f32, f32, *mut *mut c_void, *mut usize) -> bool>,
    pub snapshot_free: Option<unsafe extern "C" fn(*mut c_void, usize)>,
    pub compare_png:
        Option<unsafe extern "C" fn(*const c_void, usize, *const c_void, usize, f32) -> f32>,
}

/// Load the Swift bridge dylib and resolve all symbols.
pub fn load(path: &str) -> Result<Fns, String> {
    unsafe {
        // Load SwiftUI framework
        dlopen(
            c"/System/Library/Frameworks/SwiftUI.framework/SwiftUI".as_ptr(),
            1,
        );

        let cpath = CString::new(path).unwrap();
        let h = dlopen(cpath.as_ptr(), 2);
        if h.is_null() {
            return Err(format!("Failed to load {path}"));
        }

        let snap_ptr = dlsym(h, c"snapshot_view_handle".as_ptr());
        let free_ptr = dlsym(h, c"free_snapshot".as_ptr());
        let cmp_ptr = dlsym(h, c"compare_png_bytes".as_ptr());

        Ok(Fns {
            text: std::mem::transmute(sym(h, c"swiftui_text")),
            styled_text: std::mem::transmute(sym(h, c"swiftui_text_styled")),
            system_image: std::mem::transmute(sym(h, c"swiftui_system_image")),
            spacer: std::mem::transmute(sym(h, c"swiftui_spacer")),
            divider: std::mem::transmute(sym(h, c"swiftui_divider")),
            color: std::mem::transmute(sym(h, c"swiftui_color")),
            progress: std::mem::transmute(sym(h, c"swiftui_progress")),
            toggle: std::mem::transmute(sym(h, c"swiftui_toggle")),
            textfield: std::mem::transmute(sym(h, c"swiftui_textfield")),
            button: std::mem::transmute(sym(h, c"swiftui_button")),
            vstack: std::mem::transmute(sym(h, c"swiftui_vstack")),
            hstack: std::mem::transmute(sym(h, c"swiftui_hstack")),
            zstack: std::mem::transmute(sym(h, c"swiftui_zstack")),
            scroll_view: std::mem::transmute(sym(h, c"swiftui_scroll_view")),
            padding: std::mem::transmute(sym(h, c"swiftui_padding")),
            frame: std::mem::transmute(sym(h, c"swiftui_frame")),
            background_color: std::mem::transmute(sym(h, c"swiftui_background_color")),
            corner_radius: std::mem::transmute(sym(h, c"swiftui_corner_radius")),
            opacity: std::mem::transmute(sym(h, c"swiftui_opacity")),
            border: std::mem::transmute(sym(h, c"swiftui_border")),
            foreground_color: std::mem::transmute(sym(h, c"swiftui_foreground_color")),
            shadow: std::mem::transmute(sym(h, c"swiftui_shadow")),
            offset: std::mem::transmute(sym(h, c"swiftui_offset")),
            scale: std::mem::transmute(sym(h, c"swiftui_scale")),
            rotation: std::mem::transmute(sym(h, c"swiftui_rotation")),
            hidden: std::mem::transmute(sym(h, c"swiftui_hidden")),
            disabled: std::mem::transmute(sym(h, c"swiftui_disabled")),
            overlay: std::mem::transmute(sym(h, c"swiftui_overlay")),
            clip_circle: std::mem::transmute(sym(h, c"swiftui_clip_circle")),
            font_system: std::mem::transmute(sym(h, c"swiftui_font_system")),
            label: std::mem::transmute(sym(h, c"swiftui_label")),
            slider: std::mem::transmute(sym(h, c"swiftui_slider")),
            link: std::mem::transmute(sym(h, c"swiftui_link")),
            on_tap: std::mem::transmute(sym(h, c"swiftui_on_tap")),
            on_long_press: std::mem::transmute(sym(h, c"swiftui_on_long_press")),
            bound_textfield: std::mem::transmute(sym(h, c"swiftui_bound_textfield")),
            bound_toggle: std::mem::transmute(sym(h, c"swiftui_bound_toggle")),
            bound_slider: std::mem::transmute(sym(h, c"swiftui_bound_slider")),
            list: std::mem::transmute(sym(h, c"swiftui_list")),
            sheet: std::mem::transmute(sym(h, c"swiftui_sheet")),
            alert: std::mem::transmute(sym(h, c"swiftui_alert")),
            animation: std::mem::transmute(sym(h, c"swiftui_animation")),
            blur: std::mem::transmute(sym(h, c"swiftui_blur")),
            brightness: std::mem::transmute(sym(h, c"swiftui_brightness")),
            saturation: std::mem::transmute(sym(h, c"swiftui_saturation")),
            grayscale: std::mem::transmute(sym(h, c"swiftui_grayscale")),
            help_text: std::mem::transmute(sym(h, c"swiftui_help")),
            line_limit: std::mem::transmute(sym(h, c"swiftui_line_limit")),
            fixed_size_mod: std::mem::transmute(sym(h, c"swiftui_fixed_size")),
            aspect_ratio: std::mem::transmute(sym(h, c"swiftui_aspect_ratio")),
            clipped: std::mem::transmute(sym(h, c"swiftui_clipped")),
            tint: std::mem::transmute(sym(h, c"swiftui_tint")),
            badge: std::mem::transmute(sym(h, c"swiftui_badge")),
            secure_field: std::mem::transmute(sym(h, c"swiftui_secure_field")),
            text_editor: std::mem::transmute(sym(h, c"swiftui_text_editor")),
            stepper: std::mem::transmute(sym(h, c"swiftui_stepper")),
            group_box: std::mem::transmute(sym(h, c"swiftui_group_box")),
            tabview: std::mem::transmute(sym(h, c"swiftui_tabview")),
            bound_picker: std::mem::transmute(sym(h, c"swiftui_bound_picker")),
            menu: std::mem::transmute(sym(h, c"swiftui_menu")),
            context_menu: std::mem::transmute(sym(h, c"swiftui_context_menu")),
            navigation_title: std::mem::transmute(sym(h, c"swiftui_navigation_title")),
            toolbar: std::mem::transmute(sym(h, c"swiftui_toolbar")),
            grid: std::mem::transmute(sym(h, c"swiftui_grid")),
            form: std::mem::transmute(sym(h, c"swiftui_form")),
            section: std::mem::transmute(sym(h, c"swiftui_section")),
            on_appear: std::mem::transmute(sym(h, c"swiftui_on_appear")),
            on_disappear: std::mem::transmute(sym(h, c"swiftui_on_disappear")),
            bold_mod: std::mem::transmute(sym(h, c"swiftui_bold")),
            italic_mod: std::mem::transmute(sym(h, c"swiftui_italic")),
            popover: std::mem::transmute(sym(h, c"swiftui_popover")),
            color_invert: std::mem::transmute(sym(h, c"swiftui_color_invert")),
            ignores_safe_area: std::mem::transmute(sym(h, c"swiftui_ignores_safe_area")),
            confirmation_dialog: std::mem::transmute(sym(h, c"swiftui_confirmation_dialog")),
            keyboard_shortcut: std::mem::transmute(sym(h, c"swiftui_keyboard_shortcut")),
            focusable: std::mem::transmute(sym(h, c"swiftui_focusable")),
            truncation_mode: std::mem::transmute(sym(h, c"swiftui_truncation_mode")),
            multiline_alignment: std::mem::transmute(sym(h, c"swiftui_multiline_alignment")),
            minimum_scale_factor: std::mem::transmute(sym(h, c"swiftui_minimum_scale_factor")),
            accessibility_label: std::mem::transmute(sym(h, c"swiftui_accessibility_label")),
            accessibility_hint: std::mem::transmute(sym(h, c"swiftui_accessibility_hint")),
            accessibility_hidden: std::mem::transmute(sym(h, c"swiftui_accessibility_hidden")),
            accessibility_value: std::mem::transmute(sym(h, c"swiftui_accessibility_value")),
            disclosure_group: std::mem::transmute(sym(h, c"swiftui_disclosure_group")),
            labeled_content: std::mem::transmute(sym(h, c"swiftui_labeled_content")),
            navigation_split_view: std::mem::transmute(sym(h, c"swiftui_navigation_split_view")),
            content_unavailable: std::mem::transmute(sym(h, c"swiftui_content_unavailable")),
            share_link: std::mem::transmute(sym(h, c"swiftui_share_link")),
            release: std::mem::transmute(sym(h, c"swiftui_release")),
            retain: std::mem::transmute(sym(h, c"swiftui_retain")),
            show_window: std::mem::transmute(sym(h, c"swiftui_show_window")),
            snapshot: if snap_ptr.is_null() {
                None
            } else {
                Some(std::mem::transmute(snap_ptr))
            },
            snapshot_free: if free_ptr.is_null() {
                None
            } else {
                Some(std::mem::transmute(free_ptr))
            },
            compare_png: if cmp_ptr.is_null() {
                None
            } else {
                Some(std::mem::transmute(cmp_ptr))
            },
        })
    }
}
