//! Generate Rust FFI bindings matching the Swift @_cdecl helpers.

use crate::parser::*;

pub fn generate_rust(module: &str, types: &[&TypeInfo]) -> String {
    let mut out = String::new();
    let mod_lower = module.to_lowercase();

    out.push_str(&format!("//! Auto-generated Rust bindings for {module}\n"));
    out.push_str("//! Generated by swift-bridge-gen\n\n");
    out.push_str("#![allow(non_snake_case, dead_code)]\n\n");
    out.push_str("use core::ffi::c_void;\n\n");

    // Handle type
    out.push_str("/// Opaque handle to a Swift object.\n");
    out.push_str("pub type Handle = *mut c_void;\n\n");

    // Release function
    out.push_str("unsafe extern \"C\" {\n");
    out.push_str("    pub fn bridge_release(handle: Handle);\n");
    out.push_str("}\n\n");

    // RAII wrapper
    out.push_str("/// RAII wrapper around a Swift handle.\n");
    out.push_str("pub struct Owned(Handle);\n\n");
    out.push_str("impl Owned {\n");
    out.push_str("    pub fn new(h: Handle) -> Option<Self> { if h.is_null() { None } else { Some(Self(h)) } }\n");
    out.push_str("    pub fn raw(&self) -> Handle { self.0 }\n");
    out.push_str("}\n\n");
    out.push_str("impl Drop for Owned {\n");
    out.push_str("    fn drop(&mut self) { unsafe { bridge_release(self.0) } }\n");
    out.push_str("}\n\n");

    for ty in types {
        generate_type_bindings(&mut out, module, &mod_lower, ty);
    }

    out
}

fn generate_type_bindings(out: &mut String, module: &str, mod_lower: &str, ty: &TypeInfo) {
    let prefix = snake_case(&ty.name);
    out.push_str(&format!("// ── {} ──\n\n", ty.name));

    let mut externs = Vec::new();
    let mut methods = Vec::new();

    // Constructors
    for (i, ctor) in ty.constructors.iter().enumerate() {
        let suffix = if i == 0 {
            String::new()
        } else {
            format!("_{i}")
        };
        let cdecl_name = format!("{mod_lower}_{prefix}_init{suffix}");

        let params = rust_bridgeable_params(&ctor.params);
        if params.is_none() {
            continue;
        }
        let params = params.unwrap();

        let extern_params = params
            .iter()
            .map(|(name, ty)| format!("{name}: {ty}"))
            .collect::<Vec<_>>()
            .join(", ");

        let ret = if ctor.is_failable { "Handle" } else { "Handle" };
        externs.push(format!(
            "    pub fn {cdecl_name}({extern_params}) -> {ret};"
        ));

        // Safe wrapper
        let safe_params = params
            .iter()
            .filter(|(_, ty)| ty != "usize") // skip length params
            .map(|(name, ty)| {
                if ty == "*const u8" {
                    format!("{name}: &str")
                } else {
                    format!("{name}: {ty}")
                }
            })
            .collect::<Vec<_>>()
            .join(", ");

        let call_args = params
            .iter()
            .map(|(name, ty)| {
                if ty == "*const u8" {
                    format!("{name}.as_ptr()")
                } else if name.ends_with("_len") {
                    let base = name.strip_suffix("_len").unwrap();
                    format!("{base}.len()")
                } else {
                    name.clone()
                }
            })
            .collect::<Vec<_>>()
            .join(", ");

        let fn_name = if i == 0 {
            "new".to_string()
        } else {
            format!("new_{i}")
        };
        methods.push(format!(
            "    pub fn {fn_name}({safe_params}) -> Option<Owned> {{\n        \
                Owned::new(unsafe {{ {cdecl_name}({call_args}) }})\n    }}"
        ));
    }

    // Properties
    for prop in &ty.properties {
        if !prop.has_getter || prop.is_static {
            continue;
        }
        if !is_rust_bridgeable_return(&prop.swift_type) {
            continue;
        }

        let cdecl_name = format!("{mod_lower}_{prefix}_get_{}", snake_case(&prop.name));
        let ret_ty = rust_return_type(&prop.swift_type);
        externs.push(format!(
            "    pub fn {cdecl_name}(handle: Handle) -> {ret_ty};"
        ));

        methods.push(format!(
            "    pub fn get_{}(&self) -> {ret_ty} {{\n        \
                unsafe {{ {cdecl_name}(self.0) }}\n    }}",
            snake_case(&prop.name)
        ));
    }

    // Methods
    for (i, method) in ty.methods.iter().enumerate() {
        if method.is_static {
            continue;
        }
        let params = rust_bridgeable_params(&method.params);
        if params.is_none() {
            continue;
        }
        if !is_rust_bridgeable_return(&method.return_type) {
            continue;
        }
        let params = params.unwrap();

        let suffix = if i == 0 {
            String::new()
        } else {
            format!("_{i}")
        };
        let cdecl_name = format!("{mod_lower}_{prefix}_{}{suffix}", snake_case(&method.name));

        let mut extern_params = vec!["handle: Handle".to_string()];
        extern_params.extend(params.iter().map(|(n, t)| format!("{n}: {t}")));
        let ret_ty = rust_return_type(&method.return_type);
        externs.push(format!(
            "    pub fn {cdecl_name}({}) -> {ret_ty};",
            extern_params.join(", ")
        ));
    }

    // Emit extern block
    if !externs.is_empty() {
        out.push_str("unsafe extern \"C\" {\n");
        for e in &externs {
            out.push_str(e);
            out.push('\n');
        }
        out.push_str("}\n\n");
    }

    // Emit type wrapper
    if !methods.is_empty() {
        out.push_str(&format!("pub struct {}(Handle);\n\n", ty.name));
        out.push_str(&format!("impl {} {{\n", ty.name));
        for m in &methods {
            out.push_str(m);
            out.push('\n');
        }
        out.push_str("}\n\n");
        out.push_str(&format!("impl Drop for {} {{\n", ty.name));
        out.push_str("    fn drop(&mut self) { unsafe { bridge_release(self.0) } }\n");
        out.push_str("}\n\n");
    }
}

fn rust_bridgeable_params(params: &[ParamInfo]) -> Option<Vec<(String, String)>> {
    let mut result = Vec::new();
    for (i, p) in params.iter().enumerate() {
        let label = p.label.clone().unwrap_or_else(|| format!("arg{i}"));
        match p.swift_type.name.as_str() {
            "String" => {
                result.push((label.clone(), "*const u8".to_string()));
                result.push((format!("{label}_len"), "usize".to_string()));
            }
            "Int" | "Int64" => result.push((label, "i64".to_string())),
            "Int32" => result.push((label, "i32".to_string())),
            "UInt" | "UInt64" => result.push((label, "u64".to_string())),
            "UInt32" => result.push((label, "u32".to_string())),
            "Bool" => result.push((label, "bool".to_string())),
            "Double" => result.push((label, "f64".to_string())),
            "Float" => result.push((label, "f32".to_string())),
            _ => return None,
        }
    }
    Some(result)
}

fn is_rust_bridgeable_return(ty: &SwiftType) -> bool {
    matches!(
        ty.name.as_str(),
        "Void"
            | "String"
            | "Int"
            | "Int32"
            | "Int64"
            | "UInt"
            | "Bool"
            | "Double"
            | "Float"
            | "Optional"
    )
}

fn rust_return_type(ty: &SwiftType) -> String {
    match ty.name.as_str() {
        "Void" => "()".to_string(),
        "Int" | "Int64" => "i64".to_string(),
        "Int32" => "i32".to_string(),
        "UInt" | "UInt64" => "u64".to_string(),
        "Bool" => "bool".to_string(),
        "Double" => "f64".to_string(),
        "Float" => "f32".to_string(),
        "String" => "Handle".to_string(),
        _ => "Handle".to_string(),
    }
}

fn snake_case(s: &str) -> String {
    let mut r = String::new();
    let chars: Vec<char> = s.chars().collect();
    for (i, &c) in chars.iter().enumerate() {
        if c.is_uppercase() && i > 0 {
            let prev_up = i > 0 && chars[i - 1].is_uppercase();
            let next_lo = chars.get(i + 1).map(|x| x.is_lowercase()).unwrap_or(false);
            if !prev_up || next_lo {
                r.push('_');
            }
        }
        r.extend(c.to_lowercase());
    }
    r
}
