//! Generate Swift @_cdecl helper functions.

use crate::parser::*;

pub fn generate_swift(module: &str, types: &[&TypeInfo]) -> String {
    let mut out = String::new();
    out.push_str(&format!("// Auto-generated Swift bridge for {module}\n"));
    out.push_str("// Generated by swift-bridge-gen\n\n");
    out.push_str(&format!("import {module}\n"));
    out.push_str("import Foundation\n\n");

    out.push_str("public typealias Handle = UnsafeMutableRawPointer\n\n");

    out.push_str(
        "func box<T: AnyObject>(_ obj: T) -> Handle { Unmanaged.passRetained(obj).toOpaque() }\n",
    );
    out.push_str("func boxValue<T>(_ val: T) -> Handle { Unmanaged.passRetained(Wrapper(val)).toOpaque() }\n");
    out.push_str("func unbox<T>(_ handle: Handle) -> T { Unmanaged<Wrapper<T>>.fromOpaque(handle).takeUnretainedValue().value }\n");
    out.push_str(
        "class Wrapper<T>: NSObject { let value: T; init(_ v: T) { self.value = v } }\n\n",
    );

    out.push_str("@_cdecl(\"bridge_release\")\n");
    out.push_str("public func bridgeRelease(_ h: Handle) { Unmanaged<AnyObject>.fromOpaque(h).release() }\n\n");

    for ty in types {
        generate_type_bridge(&mut out, module, ty);
    }
    out
}

fn generate_type_bridge(out: &mut String, module: &str, ty: &TypeInfo) {
    let prefix = snake_case(&ty.name);
    let mod_lower = module.to_lowercase();
    out.push_str(&format!("// ── {} ──\n\n", ty.name));

    for (i, ctor) in ty.constructors.iter().enumerate() {
        let suffix = if i == 0 { "" } else { &format!("_{i}") };
        let cdecl = format!("{mod_lower}_{prefix}_init{suffix}");

        let mut c_params = Vec::new();
        let mut swift_args = Vec::new();
        let mut ok = true;

        for p in &ctor.params {
            let lbl = p.label.as_deref().unwrap_or("arg");
            match p.swift_type.name.as_str() {
                "String" => {
                    c_params.push(format!(
                        "_ {lbl}_ptr: UnsafePointer<UInt8>, _ {lbl}_len: Int"
                    ));
                    let s_arg = format!("String(bytes: UnsafeBufferPointer(start: {lbl}_ptr, count: {lbl}_len), encoding: .utf8) ?? \"\"");
                    if let Some(l) = &p.label {
                        swift_args.push(format!("{l}: {s_arg}"));
                    } else {
                        swift_args.push(s_arg);
                    }
                }
                "Int" | "Int32" | "Int64" | "UInt" | "Bool" | "Double" | "Float" => {
                    c_params.push(format!("_ {lbl}: {}", p.swift_type.name));
                    if let Some(l) = &p.label {
                        swift_args.push(format!("{l}: {lbl}"));
                    } else {
                        swift_args.push(lbl.to_string());
                    }
                }
                _ => {
                    ok = false;
                    break;
                }
            }
        }
        if !ok {
            continue;
        }

        let ret = if ctor.is_failable {
            "Handle?"
        } else {
            "Handle"
        };
        out.push_str(&format!("@_cdecl(\"{cdecl}\")\n"));
        out.push_str(&format!(
            "public func {cdecl}({}) -> {ret} {{\n",
            c_params.join(", ")
        ));

        let args_str = swift_args.join(", ");
        let is_class = ty.kind == TypeKind::Class;

        if ctor.is_failable {
            out.push_str(&format!(
                "    guard let v = {}({args_str}) else {{ return nil }}\n",
                ty.name
            ));
            out.push_str(&format!(
                "    return {}(v)\n",
                if is_class { "box" } else { "boxValue" }
            ));
        } else {
            out.push_str(&format!(
                "    {}({}({args_str}))\n",
                if is_class { "box" } else { "boxValue" },
                ty.name
            ));
        }
        out.push_str("}\n\n");
    }

    // Properties
    for prop in &ty.properties {
        if !prop.has_getter || prop.is_static {
            continue;
        }
        let ret = match prop.swift_type.name.as_str() {
            "Int" | "Int32" | "Int64" | "UInt" | "Bool" | "Double" | "Float" => {
                prop.swift_type.name.clone()
            }
            "String" => "Handle".to_string(),
            _ => continue,
        };
        let cdecl = format!("{mod_lower}_{prefix}_get_{}", snake_case(&prop.name));
        out.push_str(&format!("@_cdecl(\"{cdecl}\")\n"));
        out.push_str(&format!("public func {cdecl}(_ h: Handle) -> {ret} {{\n"));
        let is_class = ty.kind == TypeKind::Class;
        if is_class {
            out.push_str(&format!(
                "    let o = Unmanaged<{}>.fromOpaque(h).takeUnretainedValue()\n",
                ty.name
            ));
        } else {
            out.push_str(&format!("    let o: {} = unbox(h)\n", ty.name));
        }
        let expr = format!("o.{}", prop.name);
        if ret == "Handle" {
            out.push_str(&format!("    return boxValue({expr})\n"));
        } else {
            out.push_str(&format!("    return {expr}\n"));
        }
        out.push_str("}\n\n");
    }
}

fn snake_case(s: &str) -> String {
    let mut r = String::new();
    let chars: Vec<char> = s.chars().collect();
    for (i, &c) in chars.iter().enumerate() {
        if c.is_uppercase() && i > 0 {
            let prev_up = i > 0 && chars[i - 1].is_uppercase();
            let next_lo = chars.get(i + 1).map(|x| x.is_lowercase()).unwrap_or(false);
            if !prev_up || next_lo {
                r.push('_');
            }
        }
        r.extend(c.to_lowercase());
    }
    r
}
