/* automatically generated by rust-bindgen 0.69.4 */

#![allow(dead_code, non_snake_case, non_camel_case_types, non_upper_case_globals, improper_ctypes)]
pub type _Tp = ();

pub const REGISTER_SUBSTITUTION_PREFIX: &[u8; 1] = b"\0";
pub const REGISTER_PREFIX: &[u8; 2] = b"x\0";
