/* automatically generated by rust-bindgen 0.69.4 */

#![allow(
    dead_code,
    non_snake_case,
    non_camel_case_types,
    non_upper_case_globals,
    improper_ctypes
)]
pub type _Tp = ();

pub const _LIBCPP_ABI_VERSION: u32 = 1;
pub const _LIBCPP_ABI_FORCE_ITANIUM: u32 = 0;
pub const _LIBCPP_ABI_FORCE_MICROSOFT: u32 = 0;
pub const _LIBCPP_HAS_THREADS: u32 = 1;
pub const _LIBCPP_HAS_MONOTONIC_CLOCK: u32 = 1;
pub const _LIBCPP_HAS_TERMINAL: u32 = 1;
pub const _LIBCPP_HAS_MUSL_LIBC: u32 = 0;
pub const _LIBCPP_HAS_THREAD_API_PTHREAD: u32 = 0;
pub const _LIBCPP_HAS_THREAD_API_EXTERNAL: u32 = 0;
pub const _LIBCPP_HAS_THREAD_API_WIN32: u32 = 0;
pub const _LIBCPP_HAS_THREAD_API_C11: u32 = 0;
pub const _LIBCPP_HAS_VENDOR_AVAILABILITY_ANNOTATIONS: u32 = 1;
pub const _LIBCPP_HAS_FILESYSTEM: u32 = 1;
pub const _LIBCPP_HAS_RANDOM_DEVICE: u32 = 1;
pub const _LIBCPP_HAS_LOCALIZATION: u32 = 1;
pub const _LIBCPP_HAS_UNICODE: u32 = 1;
pub const _LIBCPP_HAS_WIDE_CHARACTERS: u32 = 1;
pub const _LIBCPP_HAS_TIME_ZONE_DATABASE: u32 = 0;
pub const _LIBCPP_INSTRUMENTED_WITH_ASAN: u32 = 0;
pub const _LIBCPP_HARDENING_MODE_DEFAULT: u32 = 2;
pub const _LIBCPP_OBJECT_FORMAT_MACHO: u32 = 1;
pub const _LIBCPP_STD_VER: u32 = 17;
pub const _LIBCPP_HAS_RTTI: u32 = 1;
pub const _LIBCPP_HAS_EXCEPTIONS: u32 = 1;
pub const _LIBCPP_INTRODUCED_IN_LLVM_20: u32 = 1;
pub const _LIBCPP_INTRODUCED_IN_LLVM_19: u32 = 1;
pub const _LIBCPP_INTRODUCED_IN_LLVM_18: u32 = 1;
pub const _LIBCPP_INTRODUCED_IN_LLVM_16: u32 = 1;
pub const _LIBCPP_INTRODUCED_IN_LLVM_15: u32 = 1;
pub const _LIBCPP_INTRODUCED_IN_LLVM_14: u32 = 1;
pub const _LIBCPP_INTRODUCED_IN_LLVM_12: u32 = 1;
pub const _LIBCPP_INTRODUCED_IN_LLVM_11: u32 = 1;
pub const _LIBCPP_INTRODUCED_IN_LLVM_9: u32 = 1;
pub const _LIBCPP_INTRODUCED_IN_LLVM_4: u32 = 1;
pub const _LIBCPP_AVAILABILITY_HAS_BAD_OPTIONAL_ACCESS: u32 = 1;
pub const _LIBCPP_AVAILABILITY_HAS_BAD_VARIANT_ACCESS: u32 = 1;
pub const _LIBCPP_AVAILABILITY_HAS_BAD_ANY_CAST: u32 = 1;
pub const _LIBCPP_AVAILABILITY_HAS_FILESYSTEM_LIBRARY: u32 = 1;
pub const _LIBCPP_AVAILABILITY_HAS_SYNC: u32 = 1;
pub const _LIBCPP_AVAILABILITY_HAS_ADDITIONAL_IOSTREAM_EXPLICIT_INSTANTIATIONS_1: u32 = 1;
pub const _LIBCPP_AVAILABILITY_HAS_TO_CHARS_FLOATING_POINT: u32 = 1;
pub const _LIBCPP_AVAILABILITY_HAS_VERBOSE_ABORT: u32 = 1;
pub const _LIBCPP_AVAILABILITY_HAS_PMR: u32 = 1;
pub const _LIBCPP_AVAILABILITY_HAS_INIT_PRIMARY_EXCEPTION: u32 = 1;
pub const _LIBCPP_AVAILABILITY_HAS_PRINT: u32 = 1;
pub const _LIBCPP_AVAILABILITY_HAS_TZDB: u32 = 1;
pub const _LIBCPP_AVAILABILITY_HAS_BAD_FUNCTION_CALL_KEY_FUNCTION: u32 = 1;
pub const _LIBCPP_AVAILABILITY_HAS_BAD_EXPECTED_ACCESS_KEY_FUNCTION: u32 = 1;
pub const _LIBCPP_AVAILABILITY_HAS_FROM_CHARS_FLOATING_POINT: u32 = 1;
pub const _LIBCPP_VERSION: u32 = 200100;
pub const _LIBCPP_HARDENING_MODE_NONE: u32 = 2;
pub const _LIBCPP_HARDENING_MODE_FAST: u32 = 4;
pub const _LIBCPP_HARDENING_MODE_EXTENSIVE: u32 = 16;
pub const _LIBCPP_HARDENING_MODE_DEBUG: u32 = 8;
pub const _LIBCPP_HARDENING_MODE: u32 = 2;
pub const _LIBCPP_HAS_EXPERIMENTAL_LIBRARY: u32 = 0;
pub const _LIBCPP_HAS_EXPERIMENTAL_PSTL: u32 = 0;
pub const _LIBCPP_HAS_EXPERIMENTAL_TZDB: u32 = 0;
pub const _LIBCPP_HAS_EXPERIMENTAL_SYNCSTREAM: u32 = 0;
pub const _LIBCPP_HAS_OPEN_WITH_WCHAR: u32 = 0;
pub const _LIBCPP_HAS_BITSCAN64: u32 = 0;
pub const _LIBCPP_HAS_OBJC_ARC: u32 = 0;
pub const _LIBCPP_HAS_OBJC_ARC_WEAK: u32 = 0;
pub const _LIBCPP_HAS_EXTENSION_BLOCKS: u32 = 1;
pub const _LIBCPP_HAS_BLOCKS_RUNTIME: u32 = 1;
pub const _LIBCPP_HAS_ASAN: u32 = 0;
pub const _LIBCPP_HAS_INT128: u32 = 1;
pub const _LIBCPP_LOCALE__L_EXTENSIONS: u32 = 1;
pub const _LIBCPP_HAS_LIBRARY_ALIGNED_ALLOCATION: u32 = 1;
pub const _LIBCPP_HAS_ALIGNED_ALLOCATION: u32 = 1;
pub const _LIBCPP_HAS_C11_ALIGNED_ALLOC: u32 = 1;
pub const _LIBCPP_HAS_CHAR8_T: u32 = 0;
pub const _LIBCPP_HAS_COND_CLOCKWAIT: u32 = 0;
pub const _LIBCPP_HAS_TRIVIAL_MUTEX_DESTRUCTION: u32 = 0;
pub const _LIBCPP_HAS_TRIVIAL_CONDVAR_DESTRUCTION: u32 = 0;
pub const _LIBCPP_HAS_C_ATOMIC_IMP: u32 = 1;
pub const _LIBCPP_HAS_GCC_ATOMIC_IMP: u32 = 0;
pub const _LIBCPP_HAS_EXTERNAL_ATOMIC_IMP: u32 = 0;
pub const _LIBCPP_HAS_ATOMIC_HEADER: u32 = 1;
pub const _LIBCPP_HAS_THREAD_SAFETY_ANNOTATIONS: u32 = 0;
pub const _LIBCPP_HAS_C8RTOMB_MBRTOC8: u32 = 0;
pub const _LIBCPP_HAS_EXPLICIT_THIS_PARAMETER: u32 = 0;
pub const SWIFT_COMPILER_IS_MSVC: u32 = 0;
pub const SWIFT_BUG_REPORT_URL: &[u8; 47] = b"https://swift.org/contributing/#reporting-bugs\0";
pub const SWIFT_BUG_REPORT_MESSAGE_BASE: &[u8; 69] =
    b"submit a bug report (https://swift.org/contributing/#reporting-bugs)\0";
pub const SWIFT_BUG_REPORT_MESSAGE: &[u8; 76] =
    b"please submit a bug report (https://swift.org/contributing/#reporting-bugs)\0";
pub const SWIFT_CRASH_BUG_REPORT_MESSAGE : & [u8 ; 109] = b"Please submit a bug report (https://swift.org/contributing/#reporting-bugs) and include the crash backtrace.\0" ;
pub const SWIFT_POINTER_IS_8_BYTES: u32 = 1;
pub const SWIFT_POINTER_IS_4_BYTES: u32 = 0;
pub const SWIFT_OBJC_INTEROP: u32 = 1;
pub const SWIFT_HAS_ISA_MASKING: u32 = 1;
pub const SWIFT_HAS_OPAQUE_ISAS: u32 = 0;
pub const SWIFT_STDLIB_HAS_MALLOC_TYPE: u32 = 0;
pub const SWIFT_CLASS_IS_SWIFT_MASK: u32 = 2;
pub const SWIFT_IMAGE_EXPORTS_swiftCore: u32 = 0;
pub const SWIFT_IMAGE_EXPORTS_swift_Concurrency: u32 = 0;
pub const SWIFT_IMAGE_EXPORTS_swiftDistributed: u32 = 0;
pub const SWIFT_IMAGE_EXPORTS_swift_Differentiation: u32 = 0;
pub const SWIFT_COMPACT_ABSOLUTE_FUNCTION_POINTER: u32 = 0;
pub const SWIFT_PTRAUTH: u32 = 0;
pub const TARGET_OS_RTKIT: u32 = 0;
pub const TARGET_RT_LITTLE_ENDIAN: u32 = 1;
pub const TARGET_RT_BIG_ENDIAN: u32 = 0;
pub const TARGET_RT_64_BIT: u32 = 1;
pub const TARGET_RT_MAC_CFM: u32 = 0;
pub const TARGET_RT_MAC_MACHO: u32 = 1;
pub const TARGET_CPU_ARM64: u32 = 1;
pub const TARGET_CPU_PPC: u32 = 0;
pub const TARGET_CPU_PPC64: u32 = 0;
pub const TARGET_CPU_68K: u32 = 0;
pub const TARGET_CPU_X86: u32 = 0;
pub const TARGET_CPU_X86_64: u32 = 0;
pub const TARGET_CPU_ARM: u32 = 0;
pub const TARGET_CPU_MIPS: u32 = 0;
pub const TARGET_CPU_SPARC: u32 = 0;
pub const TARGET_CPU_ALPHA: u32 = 0;
pub const SWIFT_BACKTRACE_ON_CRASH_SUPPORTED: u32 = 1;
pub const SWIFT_BACKTRACE_SECTION: &[u8; 24] = b"__DATA,swift5_backtrace\0";
pub const SWIFT_PAGE_SIZE: u32 = 16384;
pub type max_align_t = f64;
extern "C" {
    #[doc = " Return the path of the libswiftCore library.\n\n This can be used to locate files that are installed alongside the Swift\n runtime library.\n\n \\return A string containing the full path to libswiftCore.  The string is\n         owned by the runtime and should not be freed."]
    pub fn swift_getRuntimeLibraryPath() -> *const ::std::os::raw::c_char;
}
extern "C" {
    #[doc = " Return the path of the Swift root.\n\n If the path to libswiftCore is `/usr/local/swift/lib/libswiftCore.dylib`,\n this function would return `/usr/local/swift`.\n\n The path returned here can be overridden by setting the environment variable\n SWIFT_ROOT.\n\n \\return A string containing the full path to the Swift root directory, based\n         either on the location of the Swift runtime, or on the `SWIFT_ROOT`\n         environment variable if set.  The string is owned by the runtime\n         and should not be freed."]
    pub fn swift_getRootPath() -> *const ::std::os::raw::c_char;
}
extern "C" {
    #[doc = " Return the path of the specified auxiliary executable.\n\n This function will search for the auxiliary executable in the following\n paths:\n\n   <swift-root>/libexec/swift/<platform>/<name>\n   <swift-root>/libexec/swift/<name>\n   <swift-root>/bin/<name>\n   <swift-root>/<name>\n\n It will return the first of those that exists, but it does not test that\n the file is indeed executable.\n\n On Windows, it will automatically add `.exe` to the name, which means you\n do not need to special case the name for Windows.\n\n If you are using this function to locate a utility program for use by the\n runtime, you should provide a way to override its location using an\n environment variable.\n\n If the executable cannot be found, it will return nullptr.\n\n \\param name      The name of the executable to locate.\n\n \\return A string containing the full path to the executable.  This string\n         should be released with `free()` when no longer required."]
    pub fn swift_copyAuxiliaryExecutablePath(
        name: *const ::std::os::raw::c_char,
    ) -> *mut ::std::os::raw::c_char;
}
