#!/usr/bin/env python3
"""
ABI JSON → Rust code generator.

Reads the JSON Lines produced by an ABI fixture probe executable and emits:
  - #[repr(C)] struct definitions with validated field offsets (for value types)
  - *mut c_void handle type aliases + ivar offset constants (for class types)
  - Enum discriminant sketches (for simple enums)
  - RuntimeFactory method skeletons
  - @_cdecl bridge function templates to copy into RustBridge.swift

Usage:
    python3 scripts/abi_to_rust.py target/abi-discovery/<name>_probe.jsonl \
        [--module MODULE]
    python3 scripts/abi_to_rust.py - < probe.jsonl       # from stdin
"""

import json
import sys
from collections import defaultdict

SWIFT_TO_RUST = {
    "Int8": "i8", "Int16": "i16", "Int32": "i32", "Int64": "i64",
    "Int": "isize",
    "UInt8": "u8", "UInt16": "u16", "UInt32": "u32", "UInt64": "u64",
    "UInt": "usize",
    "Float": "f32", "Double": "f64",
    "Float32": "f32", "Float64": "f64",
    "Bool": "bool",
}

ENCODING_TO_RUST = {
    "c": "i8", "C": "u8",
    "s": "i16", "S": "u16",
    "i": "i32", "I": "u32",
    "l": "i32", "L": "u32",    # long is 32-bit in ObjC type encoding
    "q": "i64", "Q": "u64",
    "f": "f32", "d": "f64",
    "B": "bool",
    "@": "*mut c_void",         # object reference
    "#": "*mut c_void",         # Class
    ":": "*mut c_void",         # SEL
    "*": "*const core::ffi::c_char",   # char *
    "v": "()",
}

ENCODING_SIZE = {
    "c": 1, "C": 1, "s": 2, "S": 2,
    "i": 4, "I": 4, "l": 4, "L": 4,
    "q": 8, "Q": 8,
    "f": 4, "d": 8,
    "B": 1, "@": 8, "#": 8, ":": 8, "*": 8,
}


def rust_type(swift_type_name, encoding=None):
    if swift_type_name in SWIFT_TO_RUST:
        return SWIFT_TO_RUST[swift_type_name]
    if encoding and encoding.lstrip("0123456789") and encoding.lstrip("0123456789")[0] in ENCODING_TO_RUST:
        return ENCODING_TO_RUST[encoding.lstrip("0123456789")[0]]
    # Nested struct - use the type name directly
    if swift_type_name and swift_type_name[0].isupper():
        return swift_type_name
    return f"/* {swift_type_name} */ [u8; 0]"


def field_size_from_encoding(enc):
    if not enc:
        return None
    # Strip leading digits (ObjC encoding offset prefix)
    bare = enc.lstrip("0123456789")
    if bare:
        return ENCODING_SIZE.get(bare[0])
    return None


def snake(name):
    """Convert CamelCase or mixed to snake_case."""
    import re
    s1 = re.sub(r"([A-Z]+)([A-Z][a-z])", r"\1_\2", name)
    s2 = re.sub(r"([a-z\d])([A-Z])", r"\1_\2", s1)
    return s2.lower()


def generate(records, module="RustBridge"):
    types = {}     # name -> layout record
    fields = defaultdict(list)   # parent_name -> [field records]

    for r in records:
        k = r.get("kind", "")
        if k in ("struct", "class", "enum"):
            types[r["name"]] = r
        elif k == "field":
            fields[r["parent"]].append(r)

    lines = [
        "// AUTO-GENERATED by scripts/abi_to_rust.py",
        "// ─────────────────────────────────────────────────────────────────────",
        "// Review all types and mangled symbol names before using in production.",
        "// Step 1: Copy struct definitions to src/ or inline into your module.",
        "// Step 2: Fill in the mangled symbol TODOs with `nm -gU libFoo.dylib |",
        "//         swift-demangle` output.",
        "// Step 3: Add @_cdecl bridge skeletons to examples/RustBridge.swift.",
        "",
        "#![allow(dead_code, non_snake_case)]",
        "use core::ffi::c_void;",
        "",
    ]

    # ── Value types (struct) ─────────────────────────────────────────────────
    for name, layout in types.items():
        if layout["kind"] != "struct":
            continue
        size = layout["size"]
        stride = layout["stride"]
        align = layout["alignment"]
        flist = sorted(fields.get(name, []), key=lambda f: f["offset"])

        lines.append(f"// ── struct {name} ──────────────────────────────────────────────────────────")
        lines.append(f"// size={size}  stride={stride}  alignment={align}")
        lines.append(f"// Swift MemoryLayout<{name}> verified by ABI probe.")
        lines.append(f"// Use this repr when passing by value across the FFI boundary.")
        lines.append(f"#[repr(C, align({align}))]")
        lines.append(f"#[derive(Debug, Copy, Clone)]")
        lines.append(f"pub struct {name} {{")
        if flist:
            for f in flist:
                enc = f.get("encoding")
                fsz = f.get("size") if f.get("size", -1) >= 0 else field_size_from_encoding(enc)
                rtype = rust_type(f.get("swift_type", ""), enc)
                comment = f"offset +{f['offset']}"
                if fsz:
                    comment += f", size={fsz}"
                lines.append(f"    pub {f['name']}: {rtype},  // {comment}")
        else:
            lines.append(f"    _data: [u8; {size}],  // TODO: name the fields")
        lines.append("}")
        lines.append("")

        # Compile-time offset assertions
        if flist:
            lines.append(f"// Compile-time field offset assertions for {name}:")
            for f in flist:
                lines.append(
                    f"// const _: () = assert!(core::mem::offset_of!({name}, {f['name']}) == {f['offset']});"
                )
        lines.append("")

    # ── Class types ──────────────────────────────────────────────────────────
    for name, layout in types.items():
        if layout["kind"] != "class":
            continue
        inst_size = layout.get("instance_size", "?")
        flist = sorted(fields.get(name, []), key=lambda f: f["offset"])

        lines.append(f"// ── class {name} ──────────────────────────────────────────────────────────")
        lines.append(f"// Heap instance_size={inst_size}  reference_size=8 (pointer)")
        lines.append(f"// arm64 class header layout:")
        lines.append(f"//   +0   isa pointer        (8 bytes)")
        lines.append(f"//   +8   Swift refcount      (8 bytes)")
        lines.append(f"//   +16  first stored field  (varies)")
        lines.append(f"pub type {name}Ref = *mut c_void;")
        lines.append("")
        if flist:
            lines.append(f"impl {name}Ref {{  // extension trait pattern — use a wrapper struct in practice")
            lines.append(f"    // Field byte offsets validated by ivar_getOffset at runtime:")
        for f in flist:
            enc = f.get("encoding", "")
            fsz = f.get("size") if f.get("size", -1) >= 0 else field_size_from_encoding(enc)
            rtype = rust_type(f.get("swift_type", ""), enc)
            const_name = f"{name.upper()}_{f['name'].upper()}_OFFSET"
            lines.append(f"    pub const {const_name}: usize = {f['offset']};  // {rtype}")
        if flist:
            lines.append("}")
        lines.append("")
        lines.append(f"// RuntimeFactory usage for {name}:")
        lines.append(f"//   let obj = factory.call_allocating_init_i32(")
        lines.append(f"//       \"$s{len(module)}{module}{len(name)}{name}C..._MANGLE_TODO_cfC\",")
        lines.append(f"//       initial_value")
        lines.append(f"//   ).expect(\"{name} alloc failed\");")
        if flist:
            first = flist[0]
            lines.append(f"//   let {first['name']} = factory.read_i32_at_offset(obj, {first['offset']});")
        lines.append("")

    # ── Enum types ───────────────────────────────────────────────────────────
    for name, layout in types.items():
        if layout["kind"] != "enum":
            continue
        size = layout["size"]
        lines.append(f"// ── enum {name} ───────────────────────────────────────────────────────────")
        lines.append(f"// size={size}  stride={layout['stride']}  alignment={layout['alignment']}")
        lines.append(f"// Discriminant fits in {size} byte(s).  Check Swift source for case values.")
        lines.append(f"// For RawRepresentable enums: use the raw Int32/UInt8 value directly.")
        lines.append(f"// For enums with associated values: size includes payload + tag.")
        lines.append(f"#[repr(C)]")
        lines.append(f"#[derive(Debug, Copy, Clone, PartialEq, Eq)]")
        lines.append(f"pub struct {name}(pub [u8; {size}]);  // opaque; use @_cdecl bridges")
        lines.append("")

    # ── @_cdecl bridge templates ─────────────────────────────────────────────
    lines.append("// ── @_cdecl bridge templates (add to examples/RustBridge.swift) ─────────")
    lines.append("// Copy the relevant functions below into RustBridge.swift.")
    lines.append("//")
    for name, layout in types.items():
        lower = snake(name)
        if layout["kind"] == "struct":
            size = layout["size"]
            align = layout["alignment"]
            lines.append(f"// @_cdecl(\"swift_layout_{lower}_size\")")
            lines.append(f"// public func swift_layout_{lower}_size() -> Int32 {{ Int32(MemoryLayout<{name}>.size) }}")
            lines.append(f"// @_cdecl(\"swift_layout_{lower}_stride\")")
            lines.append(f"// public func swift_layout_{lower}_stride() -> Int32 {{ Int32(MemoryLayout<{name}>.stride) }}")
            lines.append(f"// @_cdecl(\"swift_layout_{lower}_alignment\")")
            lines.append(f"// public func swift_layout_{lower}_alignment() -> Int32 {{ Int32(MemoryLayout<{name}>.alignment) }}")
            flist = sorted(fields.get(name, []), key=lambda f: f["offset"])
            for f in flist:
                lines.append(f"// @_cdecl(\"swift_layout_{lower}_{f['name']}_offset\")")
                lines.append(f"// public func swift_layout_{lower}_{f['name']}_offset() -> Int32 {{ Int32(MemoryLayout<{name}>.offset(of: \\\\. {f['name']})!) }}")
            lines.append("//")
        elif layout["kind"] == "class":
            lines.append(f"// @_cdecl(\"swift_{lower}_new\")")
            lines.append(f"// public func swift_{lower}_new(/* args */) -> UnsafeMutableRawPointer {{")
            lines.append(f"//     Unmanaged.passRetained({name}(/* args */)).toOpaque()")
            lines.append(f"// }}")
            lines.append(f"// @_cdecl(\"swift_{lower}_drop\")")
            lines.append(f"// public func swift_{lower}_drop(_ p: UnsafeMutableRawPointer) {{")
            lines.append(f"//     _ = Unmanaged<{name}>.fromOpaque(p).takeRetainedValue()")
            lines.append(f"// }}")
            lines.append("//")
    lines.append("")

    # ── Parity check skeleton ────────────────────────────────────────────────
    lines.append("// ── Parity matrix skeleton (add to examples/runtime_raw_probe.rs) ──────")
    for name, layout in types.items():
        lower = snake(name)
        if layout["kind"] == "struct":
            lines.append(f"// let {lower}_size = factory.call_to_i32(\"swift_layout_{lower}_size\").unwrap_or(-1);")
            flist = sorted(fields.get(name, []), key=lambda f: f["offset"])
            for f in flist:
                lines.append(f"// let {lower}_{f['name']}_off = factory.call_to_i32(\"swift_layout_{lower}_{f['name']}_offset\").unwrap_or(-1);")
            lines.append(f"// println!(\"layout {lower} => size={{}}\", {lower}_size);")
        elif layout["kind"] == "class":
            lines.append(f"// // Create + inspect {name}:")
            lines.append(f"// let {lower}_obj = factory.call_allocating_init_i32(\"$s_TODO_cfC\", 0);")
            flist = sorted(fields.get(name, []), key=lambda f: f["offset"])
            if flist:
                first = flist[0]
                lines.append(f"// let {lower}_{first['name']} = factory.read_i32_at_offset({lower}_obj, {first['offset']});")
    lines.append("")

    return "\n".join(lines)


def main():
    module = "RustBridge"
    args = sys.argv[1:]
    for i, a in enumerate(args):
        if a == "--module" and i + 1 < len(args):
            module = args[i + 1]
            args = args[:i] + args[i + 2:]
            break

    path = args[0] if args else "-"

    if path == "-":
        raw_lines = sys.stdin.readlines()
    else:
        with open(path) as f:
            raw_lines = f.readlines()

    records = []
    for line in raw_lines:
        line = line.strip()
        if line:
            try:
                records.append(json.loads(line))
            except json.JSONDecodeError:
                pass   # skip non-JSON lines (e.g. compiler warnings)

    print(generate(records, module=module))


if __name__ == "__main__":
    main()
